name: Android CI

on:
  workflow_dispatch:
    inputs:
      PSRA:
        description: 'PSRA builds'
        required: false
        default: false
         
#Test the push  
  push:
    branches:
      - '**'
  pull_request:
    branches: [ akshay-test ]
  
  #Set your workflow to run every day of the week from Monday to Friday at 16:00 UTC(9:30 PM)
  schedule:
  - cron:  0 16 * * 1-5

jobs:
  PSRA:
    if: github.event.inputs.PSRA == true
    runs-on: self-hosted
    
    steps:
    - name: PSRA
      run: |
          ./gradlew referenceApp:assemblePsraRelease
          ./gradlew pimApp:assemblePsraRelease
    
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.0
      with:
        name: APK's for ReferenceApp & PIMDemoApp
        path: |
          ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/psraRelease/referenceApp-psraRelease.apk
          ${{github.workspace}}/source/pim/Source/DemoApp/app/build/outputs/apk/release/*.apk
    

    
