name: Android CI

on:
  push:
    branches: [ akshay-test ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        clean: true
        submodules: true
        lfs: true

    - name: Build & Test with Gradle
      run: |
        ./gradlew clean 
    
    - name: Build & Test with Gradle
      run: |
        ./gradlew --full-stacktrace assembleRelease referenceApp:testReleaseUnitTest AppInfra:testReleaseUnitTest uAppFwLib:testReleaseUnitTest registrationApi:testReleaseUnitTest product-registration-lib:testReleaseUnitTest iap:testReleaseUnitTest digitalCareUApp:testRelease digitalCare:testRelease mya:testReleaseUnitTest pif:testReleaseUnitTest pim:testReleaseUnitTest conversationalChatBot:testReleaseUnitTest philipsecommercesdk:testReleaseUnitTest mec:testReleaseUnitTest pimApp:testReleaseUnitTest referenceApp:testReleaseUnitTest

    - name: path to apk folder
      run: |
        pwd
        echo ${{github.workspace}}
        ls ${{github.workspace}}
     
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: app
        path: | 
          ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/apk/release/*.apk
            
    # - name: Publish To Artifactory
    #   run: |
    #       ./gradlew --full-stacktrace saveResDep saveAllResolvedDependenciesGradleFormat zipDocuments artifactoryPublish :referenceApp:printArtifactoryApkPath :AppInfra:zipcClogs :securedblibrary:zipcClogs :pim:zipcClogs :conversationalChatBot:zipcClogs :registrationApi:zipcClogs :productselection:zipcClogs :digitalCareUApp:zipcClogs :digitalCare:zipcClogs :pimApp:zipcClogs 
    #         apkname=`xargs < apkname.txt`
    #       ./gradlew -Dorg.gradle.parallel=false reportAllProjectDependencies | gzip -9 > ./allProjects.gradledependencies.gz
    #         curl -L -u readerwriter:AP4ZB7JSmiC4pZmeKfKTGLsFvV9 -X PUT "apkname/.apk/.gradledependencies.gz" -T ./allProjects.gradledependencies.gz

