name: Parameterized Builds

on:
  workflow_dispatch:
    inputs:
      PSRA:
        description: 'PSRA builds Test'
        required: false
        default: false
      LeakCanary:
        description: 'LeakCanary builds Test'
        required: false
        default: false
          
#Set your workflow to run every day of the week from Monday to Friday at 16:00 UTC(9:30 PM)
  schedule:  
  - cron:  0 18 * * 1-5
  
jobs:
  PSRA-Build:
    if: ${{github.event.inputs.PSRA}}==true
    runs-on: self-hosted
    
    steps:
    - name: PSRA build for RAP
      run: |
          ./gradlew referenceApp:assemblePsraRelease
          ./gradlew pimApp:assemblePsraRelease
          
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.0
      with:
        name: APK's for ReferenceApp & PIMDemoApp
        path: |
          ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/psraRelease/referenceApp-psraRelease.apk
          ${{github.workspace}}/source/pim/Source/DemoApp/app/build/outputs/psraRelease/pimApp-psraRelease.apk

  LeakCanary-Build:
    if: ${{github.event.inputs.LeakCanary}}==true
    runs-on: self-hosted
    
    steps:
    - name: LeakCanaryBuild
      run: |
           ./gradlew referenceApp:assembleLeakCanary
           ./gradlew pimApp:assembleLeakCanary
