name: Parameterized Builds

on:
  workflow_dispatch:
    inputs:
      PSRA:
        description: 'PSRA'
        required: false
        default: false
      LeakCanary:
        description: 'LeakCanary'
        required: false
        default: false
      JavaDocs:
        description: 'Java-Docs'
        required: false
        default: false
      HPFortify:
        description: 'HP-Fortify'
        required: false
        default: false
          
#Set your workflow to run every day of the week at 23:00 UTC(4:30 AM)
  schedule:  
  - cron:  0 23 * * 0-6
  
jobs:
  PSRA-Build:
    if: github.event.inputs.PSRA == 'true' #|| github.event_name == 'schedule'
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0
        clean: true
        submodules: true
        lfs: true

    - name: PSRA build for RAP
      shell: bash
      run: |
          ./gradlew referenceApp:assemblePsraRelease
          ./gradlew pimApp:assemblePsraRelease
    
    #print referenceApp artifactory path
    #fetch apk name from apkname.txt file which is generated in reference app's build.gradle
    #flushing psra apk to specified path
    - name: Publish PSRA apk
      shell: bash
      run: |
           ./gradlew :referenceApp:printArtifactoryApkPath
           apkname=`xargs < apkname.txt`
           PSRA_APK_NAME=${apkname/.apk/_PSRA.apk}
           curl -L -u 320049003:AP4ZB7JSmiC4pZmeKfKTGLsFvV9 -X PUT ${PSRA_APK_NAME} -T Source/rap/Source/AppFramework/appFramework/build/outputs/apk/psraRelease/referenceApp-psraRelease.apk
           curl -L -u 320049003:AP4ZB7JSmiC4pZmeKfKTGLsFvV9 -X PUT ${PSRA_APK_NAME} -T Source/pim/Source/DemoApp/app/build/outputs/apk/psraRelease/pimApp-psraRelease.apk
          
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.0
      with:
        name: PSRA APK's for ReferenceApp & PIMDemoApp
        path: |
          ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/psraRelease/referenceApp-psraRelease.apk
          ${{github.workspace}}/source/pim/Source/DemoApp/app/build/outputs/psraRelease/pimApp-psraRelease.apk

  LeakCanary-Build:
    if: github.event.inputs.LeakCanary == 'true'
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0
        clean: true
        submodules: true
        lfs: true
    
    - name: LeakCanaryBuild
      shell: bash
      run: |
           ./gradlew referenceApp:assembleLeakCanary
           ./gradlew pimApp:assembleLeakCanary
  
  JAVA-Docs:
    if: github.event.inputs.JavaDocs == 'true'
    #needs: Build
    runs-on: self-hosted
    steps:
    - name: GenerateJavaDocs
      shell: bash
      run: |
           ./gradlew :AppInfra:generateJavadocPublicApi \
           :securedblibrary:generateJavadocPublicApi \
           :registrationApi:generateJavadocPublicApi \
           :pim:generateJavadocPublicApi \
           :conversationalChatBot:generateJavadocPublicApi \
           :productselection:generateJavadocPublicApi \
           :pif:generateJavadocPublicApi \
           :digitalCare:generateJavadocPublicApi \
           :iap:generateJavadocPublicApi \
           :product-registration-lib:generateJavadocPublicApi \
           :philipsecommercesdk:generateJavadocPublicApi \
           :referenceApp:generateJavadocPublicApi \
   
  HPFortify-Build:
    if: github.event.inputs.HPFortify == 'true' #|| github.event_name == 'schedule'
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2.3.3
      with:
        fetch-depth: 0
        clean: true
        submodules: true
        lfs: true
    
    - name: HP-Fortify-Build
      shell: bash
      run: |
          chmod -R 755 .
          ./fortify.sh

#Blackduck yet to be added
