name: Android CI

on:
  push:
    branches: [ akshay-test ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    
    - name: path to apk folder
      run: |
        ls ${{github.workspace}}/Source/rap/Source/AppFramework/appFramework/build/outputs/apk/release
